module: CryptorECC
author: IBM
github_url: https://github.com/Kitura-Next/BlueECC/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false
